In [2]:
#numpy
import numpy as np

In [4]:
# creating array
array_1d = np.array([1,2,3,4,5])
array_1d.dtype
array_1d.ndim

1

In [5]:
array_2d = np.array([[1,2,3,4,5],[1,2,3,4,5]])
array_2d.dtype
array_2d.ndim

2

In [23]:
array_3d = np.array([[[1,2,3,4,5],[0,9,8,7,6]],[[1,2,3,4,5],[0,9,8,7,6]]])
array_3d.dtype
array_3d.ndim
# array_3d[1,1,2] # ---> 8
array_3d

array([[[1, 2, 3, 4, 5],
        [0, 9, 8, 7, 6]],

       [[1, 2, 3, 4, 5],
        [0, 9, 8, 7, 6]]])

In [16]:
array1_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[8,7,6],[4,3,2],[3,2,1]]])
array1_3d.ndim
array1_3d[0,3,0]
array1_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [8, 7, 6],
        [4, 3, 2],
        [3, 2, 1]]])

In [33]:
array_0d = np.array([1,2,3,4], ndmin = 2)
array_0d.ndim
# array_0d

2

In [34]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [36]:
# import matplotlib.pyplot as plt

# array_3d = np.array([[[1, 2, 3], 
#                       [4, 5, 6]], 

#                      [[7, 8, 9], 
#                       [10, 11, 12]],

#                      [[13, 14, 15], 
#                       [16, 17, 18]]])
# # Plot each 2D slice of the 3D array as a heatmap
# for i, slice_2d in enumerate(array_3d):
#     plt.figure()
#     plt.imshow(slice_2d, cmap='viridis', aspect='auto')
#     plt.title(f"Slice {i+1}")
#     plt.colorbar()
#     plt.show()


In [40]:
# creating array
# - list, dictionary
# - zeros
# - ones
# - empty
# - linspace
# - full
# - arange
# - random.randint
# - tile

zeros_arr = np.zeros((3,4))
ones_arr = np.ones((2,3))
eye_arr = np.eye(3)
empty_arr = np.empty((2,2))
linspace_arr= np.linspace(0,1,5)
full_arr = np.full((2,2),7)
arange_arr = np.arange(0,10,2)
random_arr = np.random.randint(0,10, (2,3))
tile_arr = np.tile([1,2,3], 2)
zeros_arr, ones_arr, eye_arr, empty_arr, linspace_arr, full_arr,  arange_arr, random_arr, tile_arr

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[511.77444444, 320.90222222],
        [529.39944444, 334.90222222]]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[7, 7],
        [7, 7]]),
 array([0, 2, 4, 6, 8]),
 array([[0, 5, 5],
        [4, 7, 9]]),
 array([1, 2, 3, 1, 2, 3]))

In [42]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b  # array([5, 7, 9])
result

array([5, 7, 9])

In [44]:
result = a - b  # array([-3, -3, -3])
result

array([-3, -3, -3])

In [45]:
result = a * b  # array([4, 10, 18])
result                          

array([ 4, 10, 18])

In [46]:
result = a / b  # array([0.25, 0.4, 0.5])
result

array([0.25, 0.4 , 0.5 ])

In [47]:
result = a + 5  # array([6, 7, 8])
result

array([6, 7, 8])

In [49]:
mean = np.mean(a)  # 2.0
mean

2.0

In [50]:
max_value = np.max(a)  # 3
min_value = np.min(a)  # 1
max_value ,min_value

(3, 1)

In [51]:
# Reshaping and Modifying Operations
array_2d = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
flattened = array_2d.flatten()  # array([1, 2, 3, 4, 5, 6])
flattened

array([1, 2, 3, 4, 5, 6])

In [53]:
transposed = array_2d.T  # array([[1, 4], [2, 5], [3, 6]])
transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
concatenated = np.concatenate((a, b))  # array([1, 2, 3, 4, 5, 6])
concatenated

array([1, 2, 3, 4, 5, 6])

In [60]:
# stacking
vstacked = np.vstack((a, b))  # Stack arrays vertically
hstacked = np.hstack((a, b))
dstacked = np.dstack((a, b))
vstacked, hstacked, dstacked

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([[[1, 4],
         [2, 5],
         [3, 6]]]))