In [1]:
import numpy as np
import pandas as pd

In [3]:
# How to create an empty and a full NumPy array?
arr = np.empty([3,4])
arr1 = np.full((3,4),5)
arr, arr1

(array([[ 1.46478448e-316,  0.00000000e+000,  3.39519328e-313,
         -1.26160168e+275],
        [ 6.94726214e-310,  9.33678150e-313, -2.75956161e+110,
          0.00000000e+000],
        [ 4.39718425e-322,  6.94720202e-310,  6.94726215e-310,
          1.08221785e-312]]),
 array([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]))

In [8]:
# Create a Numpy array filled with all zeros
arr = np.zeros([3,4])
arr # covert it into int

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# Create a Numpy array filled with all ones
arr = np.ones([3,3])
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# Check whether a Numpy array contains a specified row
arr = np.array([1,2,3,4,5,6]).reshape(3,2)
arr
[3,4] in arr.tolist()

True

In [27]:
# How to Remove rows in Numpy array that contains non-numeric values?
n_arr = np.array([[10.5, 22.5, 3.8], 
                  [41, np.nan, np.nan]]) 
  
print("Given array:") 
print(n_arr) 
  
print("\nRemove all rows containing non-numeric elements") 
print(n_arr[~np.isnan(n_arr).any(axis=1)]) 

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


In [28]:
# Remove single-dimensional entries from the shape of an array
arr = np.array([[[1, 2, 3]]])  # Shape (1, 1, 3)

# Removing single-dimensional entries
squeezed_arr = np.squeeze(arr)

print("Original shape:", arr.shape)
print("Squeezed shape:", squeezed_arr.shape)
print("Squeezed array:", squeezed_arr)

Original shape: (1, 1, 3)
Squeezed shape: (3,)
Squeezed array: [1 2 3]


In [29]:
# Find the number of occurrences of a sequence in a NumPy array
import numpy as np

# Create a NumPy array
arr = np.array([1, 3, 2, 1, 4, 1, 2, 3, 1, 4, 2, 1])

# Use np.bincount() and np.argmax() to find the most frequent value
most_frequent = np.bincount(arr).argmax()

print("Most frequent value:", most_frequent)

Most frequent value: 1


## creating array

In [55]:

# Create a 1D NumPy array of the first 10 even numbers.
arr = np.arange(2,21,2)
arr
# Create a 3x3 identity matrix using NumPy.
arr = np.eye(3)
arr
 # Create a NumPy array filled with zeros of shape (4, 5).
arr = np.zeros([4,5])
arr
# Create a NumPy array filled with ones of shape (2, 3).
arr = np.ones([2,3])
arr
# Create a 2D array of shape (4, 4) with values ranging from 1 to 16.
arr = np.arange(1,17).reshape(4,4)
arr
# Create an array of 10 random numbers between 0 and 1.
arr = np.random.rand(10)
arr
# Create a NumPy array with values from 10 to 50.
arr = np.arange(10,51)
arr
# Create a 5x5 array with random integer values between 1 and 100.
arr = np.random.randint(1,101 ,size=(5,5))
arr
 # Create an array with 20 evenly spaced values between 0 and 5.
arr = np.linspace(0,5,20)
arr
# Create a NumPy array using the arange() function that starts at 5 and ends at 25 with a step of 2.
arr = np.arange(5,26,2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

## array indexing

In [77]:

# Access the third element from a 1D array of your choice.
arr_1d = np.array([10, 20, 30, 40, 50])
arr_1d[2]
# Access the last element from a 1D array.
last_element = arr_1d[-1]
last_element
# Access the first row of a 2D array with shape (4, 4).
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
arr_2d[0]

# Retrieve the element at the second row and third column of a 3x3 array.
arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
arr_3x3[1,2]
last_element = arr_3x3[-1]
last_element

# Access all elements from a 1D array that are greater than a specified value.
value = 25
arr_1d = np.array([10, 20, 30, 40, 50])
specified_val = arr_1d[arr_1d > 25]
specified_val

# Access the first two elements of the second row in a 2D array.
arr_3x3[1, :2]

# Access the diagonal elements of a 3x3 matrix.
arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
diagonal_ele = np.diag(arr_3x3)
diagonal_ele

# Replace the third element of a 1D array with 100.
arr_1d = np.array([10, 20, 30, 40, 50])
arr_1d[2]=100
arr_1d

# Use negative indexing to access the last element of a 2D array.
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
arr_2d[-1,-1]

# Access the elements at even indices from a 1D array.
arr_1d = np.array([10, 20, 30, 40, 50])
arr_1d[::2]

array([10, 30, 50])

## NumPy Array Slicing

In [91]:

# Slice the first three elements from a 1D array.
arr_1d = np.array([10, 20, 30, 40, 50])
arr_1d[0:3]
# Slice the first two rows from a 3x3 matrix.
arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
arr_3x3[:2 ,:]
# Slice the last two columns from a 2D array of your choice.
arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
arr_3x3[:,1:]
# Slice a 1D array from the third element to the end.
arr_1d = np.array([10, 20, 30, 40, 50])
arr_1d[2:]
# Extract every second element from a 1D array.
arr_1d = np.array([10, 20, 30, 40, 50])
arr_1d[::2]

#Slice the middle 2x2 block from a 4x4 matrix.
matrix_4x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])
matrix_4x4[1:3, 1:3]

# Reverse the order of elements in a 1D array using slicing.
arr_1d = np.array([10, 20, 30, 40, 50])
arr_1d[::-1]

 # Extract the first two columns and last two rows from a 4x4 array.
matrix_4x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])
matrix_4x4[2:,:2]

# Slice a 2D array to get all elements except the first row.
matrix_4x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])
matrix_4x4[1:]

# Slice a 3D array to get all elements from the first plane.
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                     
                     [[7, 8, 9],
                      [10, 11, 12]],
                     
                     [[13, 14, 15],
                      [16, 17, 18]]])
array_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
# Create a NumPy array with mixed data types
mixed_array = np.array([1, 'two', 3.0])

# Identify the type of the array
mixed_dtype = mixed_array.dtype

print("Mixed data type array:", mixed_array)
print("Data type of mixed array:", mixed_dtype)


Mixed data type array: ['1' 'two' '3.0']
Data type of mixed array: <U32


## copy vs view

In [99]:
# Create a 1D array and make a copy of it. Modify the copy and check if the original changes.
# Create a 2D array and make a view of it. Modify the view and check if the original changes.
# Explain the difference between a copy and a view with an example.
# Create a view of an array and modify it. Observe how the original array is affected.
# Create a copy of a sliced array and modify the copy. Does the original array change?
# Check if a given array is a view or a copy of another array.
# Use the .base attribute to check the relationship between the original array and its view.
# Create a view of a large array and modify a small portion. Check memory usage compared to a copy.
# Create a copy of an array and change its shape. Does it affect the original array?
# Use the np.copy() function to create a deep copy of a nested array and modify it.

# Create a 1D array and make a copy of it. Modify the copy and check if the original changes.
arr_1d = np.array([10, 20, 30, 40, 50])
arr2 =arr_1d.copy()
arr2[0]=60
arr2

# Create a 2D array and make a view of it. Modify the view and check if the original changes.
arr2d= np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])
v_arr=arr2d.view()
v_arr[0,1]=20
arr2d,v_arr

(array([[ 1, 20,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 1, 20,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]))

In [101]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Transpose the matrix
transposed_array = array_2d.T

# Check its shape
print("Shape of transposed matrix:", transposed_array.shape)
transposed_array

Shape of transposed matrix: (3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [102]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])