In [2]:
#numpy
import numpy as np

In [4]:
# creating array
array_1d = np.array([1,2,3,4,5])
array_1d.dtype
array_1d.ndim

1

In [5]:
array_2d = np.array([[1,2,3,4,5],[1,2,3,4,5]])
array_2d.dtype
array_2d.ndim

2

In [23]:
array_3d = np.array([[[1,2,3,4,5],[0,9,8,7,6]],[[1,2,3,4,5],[0,9,8,7,6]]])
array_3d.dtype
array_3d.ndim
# array_3d[1,1,2] # ---> 8
array_3d

array([[[1, 2, 3, 4, 5],
        [0, 9, 8, 7, 6]],

       [[1, 2, 3, 4, 5],
        [0, 9, 8, 7, 6]]])

In [16]:
array1_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[8,7,6],[4,3,2],[3,2,1]]])
array1_3d.ndim
array1_3d[0,3,0]
array1_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [8, 7, 6],
        [4, 3, 2],
        [3, 2, 1]]])

In [33]:
array_0d = np.array([1,2,3,4], ndmin = 2)
array_0d.ndim
# array_0d

2

In [34]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [36]:
# import matplotlib.pyplot as plt

# array_3d = np.array([[[1, 2, 3], 
#                       [4, 5, 6]], 

#                      [[7, 8, 9], 
#                       [10, 11, 12]],

#                      [[13, 14, 15], 
#                       [16, 17, 18]]])
# # Plot each 2D slice of the 3D array as a heatmap
# for i, slice_2d in enumerate(array_3d):
#     plt.figure()
#     plt.imshow(slice_2d, cmap='viridis', aspect='auto')
#     plt.title(f"Slice {i+1}")
#     plt.colorbar()
#     plt.show()


In [40]:
# creating array
# - list, dictionary
# - zeros
# - ones
# - empty
# - linspace
# - full
# - arange
# - random.randint
# - tile

zeros_arr = np.zeros((3,4))
ones_arr = np.ones((2,3))
eye_arr = np.eye(3)
empty_arr = np.empty((2,2))
linspace_arr= np.linspace(0,1,5)
full_arr = np.full((2,2),7)
arange_arr = np.arange(0,10,2)
random_arr = np.random.randint(0,10, (2,3))
tile_arr = np.tile([1,2,3], 2)
zeros_arr, ones_arr, eye_arr, empty_arr, linspace_arr, full_arr,  arange_arr, random_arr, tile_arr

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[511.77444444, 320.90222222],
        [529.39944444, 334.90222222]]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[7, 7],
        [7, 7]]),
 array([0, 2, 4, 6, 8]),
 array([[0, 5, 5],
        [4, 7, 9]]),
 array([1, 2, 3, 1, 2, 3]))

In [42]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b  # array([5, 7, 9])
result

array([5, 7, 9])

In [44]:
result = a - b  # array([-3, -3, -3])
result

array([-3, -3, -3])

In [45]:
result = a * b  # array([4, 10, 18])
result                          

array([ 4, 10, 18])

In [46]:
result = a / b  # array([0.25, 0.4, 0.5])
result

array([0.25, 0.4 , 0.5 ])

In [47]:
result = a + 5  # array([6, 7, 8])
result

array([6, 7, 8])

In [49]:
mean = np.mean(a)  # 2.0
mean

2.0

In [50]:
max_value = np.max(a)  # 3
min_value = np.min(a)  # 1
max_value ,min_value

(3, 1)

In [51]:
# Reshaping and Modifying Operations
array_2d = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
flattened = array_2d.flatten()  # array([1, 2, 3, 4, 5, 6])
flattened

array([1, 2, 3, 4, 5, 6])

In [53]:
transposed = array_2d.T  # array([[1, 4], [2, 5], [3, 6]])
transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
concatenated = np.concatenate((a, b))  # array([1, 2, 3, 4, 5, 6])
concatenated

array([1, 2, 3, 4, 5, 6])

In [60]:
# stacking
vstacked = np.vstack((a, b))  # Stack arrays vertically
hstacked = np.hstack((a, b))
dstacked = np.dstack((a, b))
vstacked, hstacked, dstacked

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([[[1, 4],
         [2, 5],
         [3, 6]]]))

In [20]:
# Single Element Access:

# Given the array arr = np.array([10, 20, 30, 40, 50]), how would you access the third element?
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
arr[2]
# Negative Indexing:

# For the array arr = np.array([1, 2, 3, 4, 5]), how can you access the last element using negative indexing?
arr = np.array([1, 2, 3, 4, 5])
arr[-1]

# 2D Array Access:

# Given the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), how can you access the element in the second row and third column?
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[1,2]

# Slicing a 1D Array:

# For the array arr = np.array([10, 20, 30, 40, 50, 60]), how can you access the elements from index 2 to 4?
arr = np.array([10, 20, 30, 40, 50, 60])
arr[1:4]

# Slicing a 2D Array:

# Given the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), how would you slice the first two rows and the last two columns?
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[:2, 1:]

# Accessing Multiple Elements:

# For the array arr = np.array([10, 20, 30, 40, 50]), how can you access the elements at index 1, 3, and 4?
arr = np.array([10, 20, 30, 40, 50])
arr[[1,2,4]] # by fancy indexing

# Slicing with Steps:

# Given the array arr = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80]), how can you access every second element starting from the first element?
# Advanced Indexing
# Boolean Indexing:

# For the array arr = np.array([1, 3, 5, 7, 9, 11]), how can you access all elements greater than 5?
# Fancy Indexing:

# Given the array arr = np.array([10, 20, 30, 40, 50]), how can you access the elements at the indices [0, 2, 4] using fancy indexing?
# 3D Array Access:

# For the 3D array arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]), how can you access the element 11?





arr = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80])
arr[::2]
arr = np.array([1, 3, 5, 7, 9, 11])
arr[arr>5]
arr = np.array([10, 20, 30, 40, 50])
arr[[0,2,4]]
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[1,1,1]

11

In [68]:
# 2D Array Practice Questions
# Accessing Elements in a 2D Array:

# Given the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), how would you access the element in the last row and the first column?
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[2,0]
# Slicing a Submatrix:

# For the array arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), slice the submatrix that includes the first two rows and the last two columns.
arr[:2, 1:]
# Fancy Indexing on a 2D Array:

# Given the 2D array arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), how can you use fancy indexing to access the elements 20, 50, and 80?
arr[[0,1,2],[1,1,1]]
# Boolean Indexing in a 2D Array:

# For the array arr = np.array([[3, 6, 9], [12, 15, 18], [21, 24, 27]]), how would you extract all elements greater than 15?
arr = np.array([[3, 6, 9], [12, 15, 18], [21, 24, 27]])
arr[arr > 15]
# Setting Elements Using Slicing:

# Given the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), set all the elements in the last row to 0.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[2]=0
arr
# Transpose of a Matrix:

# For the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), find the transpose of the matrix.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.T

# Sum Across Rows and Columns:

# Given the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum across rows and columns.
# the sum across rows------>
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_across_rows = np.sum(arr, axis =1) # 1 for rows
sum_across_rows
 # the sum across columns------>
sum_across_col = np.sum(arr, axis= 0)
sum_across_col

# Diagonal Elements:

# For the array arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), extract the diagonal elements.
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
diagonal_element = np.diagonal(arr)
diagonal_element
# Flattening a 2D Array:

# Given the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), flatten the array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flatten_arr = arr.flatten()
flatten_arr
# Stacking Arrays:

# Given two 2D arrays arr1 = np.array([[1, 2], [3, 4]]) and arr2 = np.array([[5, 6], [7, 8]]), stack them vertically and horizontally.
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[5, 6], [7, 8]])
arr =np.vstack((arr1,arr2)) #vertically
arr
arr =np.hstack((arr1,arr2)) #horizontally
arr
arr1, arr2
# 3D Array Practice Questions
# Accessing Elements in a 3D Array:

# Given the 3D array arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]), how would you access the element 11?
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[1,1,1]
# Slicing a 3D Array:

# For the array arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]), slice out the subarray [[7, 8, 9], [10, 11, 12]].
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
arr[1]
# Fancy Indexing on a 3D Array:

# Given the 3D array arr = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]], [[90, 100], [110, 120]]]), how can you use fancy indexing to access the elements 10, 70, and 120?
arr = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]], [[90, 100], [110, 120]]])
arr[[0,1,2],[0,1,1],[0,0,1]]

# Boolean Indexing in a 3D Array:

# For the array arr = np.array([[[2, 4], [6, 8]], [[10, 12], [14, 16]], [[18, 20], [22, 24]]]), extract all elements greater than 10.
arr = np.array([[[2, 4], [6, 8]], [[10, 12], [14, 16]], [[18, 20], [22, 24]]])
arr[arr >10]
# Reshaping a 3D Array:

# Given the array arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]), reshape it into a 2x6 matrix.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr.reshape(2,6)
# Swapping Axes:

# For the 3D array arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]), swap the axes so that the shape changes from (2, 2, 2) to (2, 2, 2) in a different order.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
transposed = np.transpose(arr, (2, 0, 1))
# print("Transposed Array:\n", transposed)
# print("Shape:", transposed.shape)

# Sum Across a Specific Axis:

# Given the 3D array arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]), calculate the sum across the second axis.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
sum_across_axis1 = np.sum(arr, axis=1)
print("Sum across axis 1:\n", sum_across_axis1)
arr

# Broadcasting in a 3D Array:

# For the 3D array arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]), add a 1D array np.array([10, 20]) to each 2x2 matrix within the 3D array using broadcasting.
# Element-wise Multiplication:

# Given the 3D arrays arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) and arr2 = np.array([[[2, 0], [1, 3]], [[3, 1], [2, 2]]]), perform element-wise multiplication.
# Advanced Slicing:

# For the 3D array arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]), slice out the subarray [[2, 3], [5, 6], [8, 9]].



Sum across axis 1:
 [[ 4  6]
 [12 14]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# In a 3D array, the axes are indexed as follows: *************************************

# Axis 0: The first dimension (depth or the first set of matrices).
# Axis 1: The second dimension (rows in each matrix).
# Axis 2: The third dimension (columns in each row).

In [72]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[[0,1,1],[1,0,1],[0,2,2]]

array([ 4,  9, 12])

In [74]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
elements = arr[[0, 1, 1], [1, 1, 0], [0, 2, 2]]
print("Elements:", elements)


Elements: [ 4 12  9]


In [75]:
# returns only value which is higher than 42
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [78]:
arr = np.array([41, 42, 43, 44])
arr[arr > 42]

array([43, 44])